// Package pdp implements the Scalable Provable Data Possession (S-PDP) protocol
// from the paper "Provable Data Possession at Untrusted Stores" by Ateniese et al.
// A copy of the paper is in doc/provable-data-possession.pdf.
//
// # Overview
//
// S-PDP lets a client (C) verify that a remote server (S) is faithfully storing
// a file without downloading the file. The protocol has three phases:
//
//  1. Setup: C splits the file into n blocks, generates a key pair, computes a
//     cryptographic tag for each block, and uploads the blocks and tags to S. C
//     then deletes its local copies of the blocks and tags, keeping only (pk, sk).
//
//  2. Challenge: C generates a random challenge that names a subset of blocks (via
//     a pseudorandom permutation) and sends it to S. The challenge also includes a
//     public blinding factor Gs = g^s, where s is a random secret C keeps private.
//
//  3. Response & Verification: S calls GenProof to produce an aggregated proof V
//     and returns it to C. C calls CheckProof with s to verify V.
//
// # API
//
//	pk, sk := KeyGen(k)                        // client, once
//	tag_i  := TagBlock(pk, sk, block_i, i)     // client, once per block
//	// ... upload (pk, blocks, tags) to server, delete local copies ...
//
//	// -- per audit round --
//	s      := random big.Int                   // client generates per-challenge secret
//	chal   := &Challenge{C: c, K1: k1, K2: k2, Gs: g^s}
//	proof  := GenProof(pk, blocks, chal, tags) // server
//	ok     := CheckProof(pk, sk, s, tags, chal, proof) // client
//
// # Deviations from the paper
//
// Block data is SHA-256 hashed before being used as a group exponent. The paper
// treats block content as a raw integer, but in practice blocks are arbitrary-length
// byte slices. Hashing maps each block to a fixed-size value in a collision-resistant
// way. The hash is applied identically in TagBlock and GenProof, so the verification
// equation still holds.
//
// hashToQRN squares a reduced SHA-256 hash, which guarantees the output is in QR_N
// but does not produce a uniform distribution over QR_N (the paper requires uniform).
// This is a theoretical weakness that does not affect correctness and is unlikely to
// be exploitable in practice.
package pdp

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"math/big"
	"sort"
)

// PublicKey is the client's public key, shared with the server.
//
//   - N is the RSA modulus N = p*q, where p and q are safe primes.
//   - G is a generator of QR_N, the cyclic group of quadratic residues mod N,
//     which has order phi = p'*q' (where p = 2p'+1, q = 2q'+1).
type PublicKey struct {
	N *big.Int
	G *big.Int
}

// SecretKey is the client's private key. It must never be sent to the server.
//
//   - E and D satisfy E*D ≡ 1 (mod Phi); E is the RSA encryption exponent and
//     D is the decryption (tag-signing) exponent.
//   - V is a random secret used to derive per-block identifiers W_i = V || i.
//   - Phi = p'*q' is the order of QR_N, used for exponent reduction in CheckProof.
type SecretKey struct {
	E   *big.Int
	D   *big.Int
	V   []byte
	Phi *big.Int
}

// Tag is the verification metadata for a single file block, computed by TagBlock.
//
//   - T is the tag value: T = (h(W) * g^m)^d mod N.
//   - W is the block identifier W_i = V || i, kept alongside T so the verifier
//     can recompute h(W_i) during CheckProof without access to V.
type Tag struct {
	T *big.Int
	W []byte
}

// Challenge is generated by the client and sent to the server to initiate an audit.
//
//   - C is the number of blocks to challenge (must satisfy 1 <= C <= len(blocks)).
//   - K1 is a random key for the pseudorandom permutation that selects block indices.
//   - K2 is a random key for the pseudorandom function that assigns per-block coefficients.
//   - Gs is the public blinding factor g^s, where s is a random secret kept by the client.
//     The server uses Gs to compute rho = H((g^s)^μ) without learning s. The client
//     passes s (not Gs) to CheckProof to verify the response.
type Challenge struct {
	C  int
	K1 []byte
	K2 []byte
	Gs *big.Int // g^s: public blinding factor; the client keeps s secret
}

// Proof is the server's response to a Challenge, produced by GenProof.
//
//   - T is the aggregated tag product: T = ∏ tag_i^{a_j} mod N.
//   - Rho is the binding hash: rho = SHA-256((g^s)^μ mod N), where μ = Σ a_j*m_j.
type Proof struct {
	T   *big.Int
	Rho []byte
}

// generateSafePrime returns a safe prime p = 2*p' + 1 of the requested bit length,
// along with the Sophie Germain prime p'. Safe primes ensure that QR_N has a known,
// prime-order subgroup structure: |QR_N| = p'*q'.
func generateSafePrime(bits int) (p, pPrime *big.Int, err error) {
	one := big.NewInt(1)

	for {
		pPrime, err = rand.Prime(rand.Reader, bits-1)
		if err != nil {
			return nil, nil, err
		}

		// p = 2*pPrime + 1
		p = new(big.Int).Lsh(pPrime, 1)
		p.Add(p, one)

		if p.ProbablyPrime(20) {
			return p, pPrime, nil
		}
	}
}

// generateGQRN returns a generator g of QR_N — the cyclic subgroup of quadratic
// residues mod N of order p'*q'.
//
// Per §4.3 of the paper: choose a ← Z*_N such that gcd(a±1, N) = 1, then set
// g = a² mod N. Squaring maps a into QR_N. The gcd conditions ensure a ≢ ±1 mod p
// and a ≢ ±1 mod q, which excludes the elements whose squares collapse to 1.
// The probability that a random a² lands in a proper subgroup of QR_N is at most
// (p' + q') / (p'q') ≈ 1/q' + 1/p', which is negligible for large primes.
func generateGQRN(N *big.Int) (G *big.Int, err error) {
	one := big.NewInt(1)
	two := big.NewInt(2)
	nMinus1 := new(big.Int).Sub(N, one)

	for {
		// 1. sample a ∈ [1, N-1]
		a, err := rand.Int(rand.Reader, nMinus1)
		if err != nil {
			return nil, err
		}
		a.Add(a, one)

		// 2. check gcd(a, N) = 1  (a must be a unit mod N)
		if new(big.Int).GCD(nil, nil, a, N).Cmp(one) != 0 {
			continue
		}

		// 3. check gcd(a - 1, N) = 1  (avoids a ≡ 1 which gives g = 1)
		aMinus1 := new(big.Int).Sub(a, one)
		if new(big.Int).GCD(nil, nil, aMinus1, N).Cmp(one) != 0 {
			continue
		}

		// 4. check gcd(a + 1, N) = 1  (avoids a ≡ -1 which gives g = 1)
		aPlus1 := new(big.Int).Add(a, one)
		if new(big.Int).GCD(nil, nil, aPlus1, N).Cmp(one) != 0 {
			continue
		}

		// 5. g = a² mod N
		return new(big.Int).Exp(a, two, N), nil
	}
}

// hashToQRN maps an arbitrary byte string deterministically and near-uniformly
// into QR_N.
//
// Per footnote 3 of the paper, h is constructed by squaring the output of a
// full-domain hash (FDH) function over [0, N-1]. A direct SHA-256 output is
// only 256 bits, far smaller than the 2k-bit modulus, so we use MGF1
// (RFC 8017 §B.2.1) with SHA-256 to expand the input to
// ⌈(N.BitLen() + 128) / 8⌉ bytes. Reducing that value mod N introduces
// statistical bias of at most 2^{-128}, which is negligible. Squaring the
// result then maps uniformly into QR_N.
func hashToQRN(data []byte, N *big.Int) *big.Int {
	// MGF1: concatenate SHA-256(data || counter) for counter = 0, 1, 2, …
	// until we have enough bytes to make the mod-N reduction near-uniform.
	targetBytes := (N.BitLen() + 128 + 7) / 8
	var buf []byte
	for counter := uint32(0); len(buf) < targetBytes; counter++ {
		var c [4]byte
		binary.BigEndian.PutUint32(c[:], counter)
		h := sha256.New()
		h.Write(data)
		h.Write(c[:])
		buf = append(buf, h.Sum(nil)...)
	}
	x := new(big.Int).SetBytes(buf[:targetBytes])
	x.Mod(x, N)
	// x ≡ 0 mod N occurs with probability ≤ 1/N (negligible). 0 is not in Z*_N
	// and its square is not a valid QR_N element, so substitute 1 (also in QR_N).
	if x.Sign() == 0 {
		x.SetInt64(1)
	}
	return new(big.Int).Exp(x, big.NewInt(2), N)
}

// KeyGen generates a fresh key pair for the S-PDP scheme.
//
// k is the security parameter in bits; it controls the size of the safe primes
// used to build the RSA modulus (N is approximately 2k bits). The paper requires
// k ≥ 1024 for security; smaller values (e.g. k = 128) are only suitable for tests.
//
// The algorithm (§4.2 of the paper):
//  1. Generate safe primes p = 2p'+1 and q = 2q'+1; set N = p*q.
//  2. Set phi = p'*q', the order of QR_N.
//  3. Choose a random 256-bit prime e coprime to phi; compute d = e^{-1} mod phi.
//  4. Generate g, a generator of QR_N.
//  5. Draw a random secret v ∈ {0,1}^k, used to derive per-block identifiers.
func KeyGen(k int) (pk *PublicKey, sk *SecretKey, err error) {
	p, pPrime, err := generateSafePrime(k)
	if err != nil {
		return nil, nil, err
	}
	q, qPrime, err := generateSafePrime(k)
	if err != nil {
		return nil, nil, err
	}

	// N = p*q is the RSA modulus.
	N := new(big.Int).Mul(p, q)

	// phi = p'*q' is the order of QR_N.
	// Note: the full Euler totient is phi(N) = (p-1)(q-1) = 4*p'*q', but the
	// relevant group order for elements of QR_N is p'*q'.
	phi := new(big.Int).Mul(pPrime, qPrime)

	// e is a 256-bit prime chosen coprime to phi.
	// The paper requires e > λ and d > λ for some security threshold λ; 256 bits
	// is a reasonable choice.
	one := big.NewInt(1)
	var e *big.Int
	for {
		e, err = rand.Prime(rand.Reader, 256)
		if err != nil {
			return nil, nil, err
		}
		if new(big.Int).GCD(nil, nil, e, phi).Cmp(one) == 0 {
			break
		}
	}

	// d = e^{-1} mod phi; together e and d form the RSA trapdoor over QR_N.
	d := new(big.Int).ModInverse(e, phi)
	if d == nil {
		return nil, nil, fmt.Errorf("mod inverse of e mod phi failed")
	}

	// g is a generator of QR_N per the paper's construction.
	g, err := generateGQRN(N)
	if err != nil {
		return nil, nil, err
	}

	// v is a k-bit random secret used to bind block identifiers to this key pair.
	v := make([]byte, k/8)
	if _, err = rand.Read(v); err != nil {
		return nil, nil, err
	}

	pk = &PublicKey{N: N, G: g}
	sk = &SecretKey{E: e, D: d, V: v, Phi: phi}
	return pk, sk, nil
}

// TagBlock computes the verification tag for block m at position i.
//
// The algorithm (§4.2 of the paper):
//  1. Derive the block identifier W_i = V || encode(i).
//  2. Compute T = (h(W_i) * g^m)^d mod N.
//  3. Return (T, W_i).
//
// Deviation from the paper: m is SHA-256 hashed before being used as a group
// exponent, mapping arbitrary-length block data to a fixed 256-bit integer.
// GenProof applies the same hash, so the verification equation is unaffected.
//
// The tags (but not sk.V) are sent to the server along with the blocks.
func TagBlock(pk *PublicKey, sk *SecretKey, m []byte, i uint64) (*Tag, error) {
	iBytes := make([]byte, 8)
	binary.BigEndian.PutUint64(iBytes, i)

	// W_i = V || i binds the tag to both this key pair and this block index,
	// preventing a server from reordering or substituting blocks.
	Wi := make([]byte, 0, len(sk.V)+len(iBytes))
	Wi = append(Wi, sk.V...)
	Wi = append(Wi, iBytes...)

	// mInt = SHA-256(m) interpreted as a big.Int exponent.
	hm := sha256.Sum256(m)
	mInt := new(big.Int).SetBytes(hm[:])

	h := hashToQRN(Wi, pk.N)                 // h(W_i) ∈ QR_N
	gm := new(big.Int).Exp(pk.G, mInt, pk.N) // g^m mod N
	T := new(big.Int).Mul(gm, h)             // h(W_i) * g^m
	T.Mod(T, pk.N)
	T.Exp(T, sk.D, pk.N) // (h(W_i) * g^m)^d mod N

	return &Tag{T: T, W: Wi}, nil
}

// PRF is a pseudorandom function keyed by key, evaluated at integer j.
// It is used in GenProof and CheckProof to derive per-block coefficients a_j.
//
// The output is truncated to 128 bits (the first 16 bytes of HMAC-SHA-256).
// The paper leaves the coefficient length ℓ as a protocol parameter; 128 bits
// provides standard security while keeping μ = Σ a_j·m_j bounded to at most
// C×256 bits — half the size of 256-bit coefficients — which bounds the cost
// of the server-side exponentiation Gs^μ mod N.
func PRF(key []byte, j int) *big.Int {
	buf := make([]byte, 8)
	binary.BigEndian.PutUint64(buf, uint64(j))
	mac := hmac.New(sha256.New, key)
	mac.Write(buf)
	return new(big.Int).SetBytes(mac.Sum(nil)[:16]) // 128 bits
}

type prpEntry struct {
	index int
	score []byte
}

// BuildPRP constructs a pseudorandom permutation of [0, n) keyed by key.
// It assigns each index i an HMAC-SHA-256 score and sorts by score, producing
// a deterministic permutation that both client and server can reconstruct
// from the same challenge key K1 without communicating the indices directly.
func BuildPRP(key []byte, n int) []int {
	entries := make([]prpEntry, n)
	for i := range n {
		buf := make([]byte, 8)
		binary.BigEndian.PutUint64(buf, uint64(i))
		mac := hmac.New(sha256.New, key)
		mac.Write(buf)
		entries[i] = prpEntry{index: i, score: mac.Sum(nil)}
	}
	sort.Slice(entries, func(i, j int) bool {
		return bytes.Compare(entries[i].score, entries[j].score) < 0
	})
	perm := make([]int, n)
	for i := range n {
		perm[i] = entries[i].index
	}
	return perm
}

// GenProof is run by the server to produce a proof of possession for the challenged blocks.
//
// The algorithm (§4.2 of the paper):
//  1. Use BuildPRP(K1, n) to select C block indices i_1 … i_C.
//  2. Use PRF(K2, j) to derive coefficient a_j for each selected block.
//  3. Compute the aggregated tag T = ∏ tag_{i_j}^{a_j} mod N.
//  4. Compute μ = Σ a_j * SHA-256(block_{i_j}) as an integer (no modular reduction;
//     the verification equation holds regardless — see math_test.go for proof).
//  5. Compute rho = SHA-256((g^s)^μ mod N), where g^s = chal.Gs.
//
// blocks and tags must be the same length and chal.C must be in [1, len(blocks)].
func GenProof(pk *PublicKey, blocks [][]byte, chal *Challenge, tags []*Tag) (*Proof, error) {
	if len(blocks) != len(tags) {
		return nil, fmt.Errorf("blocks and tags length mismatch: %d vs %d", len(blocks), len(tags))
	}
	if chal.C < 1 || chal.C > len(blocks) {
		return nil, fmt.Errorf("challenge C=%d out of range [1, %d]", chal.C, len(blocks))
	}

	perm := BuildPRP(chal.K1, len(blocks))

	T := big.NewInt(1)
	mu := big.NewInt(0)

	for j := 1; j <= chal.C; j++ {
		ij := perm[j-1] // convert 1-based challenge index to 0-based block index
		aj := PRF(chal.K2, j)
		tag := tags[ij]

		// Accumulate tag product: T = ∏ tag_i^{a_j} mod N
		term := new(big.Int).Exp(tag.T, aj, pk.N)
		T.Mul(T, term)
		T.Mod(T, pk.N)

		// Accumulate μ = Σ a_j * m_j  (m_j is the SHA-256 hash of the block,
		// matching the encoding used in TagBlock)
		hm := sha256.Sum256(blocks[ij])
		mInt := new(big.Int).SetBytes(hm[:])
		mu.Add(mu, new(big.Int).Mul(aj, mInt))
	}

	// rho = SHA-256((g^s)^μ mod N).  chal.Gs is g^s, the public blinding factor;
	// the server never learns s itself.
	gsmu := new(big.Int).Exp(chal.Gs, mu, pk.N)
	rho := sha256.Sum256(gsmu.Bytes())

	return &Proof{T: T, Rho: rho[:]}, nil
}

// CheckProof is run by the client to verify a proof returned by the server.
//
// s is the client's per-challenge secret (not transmitted to the server).
// chal.Gs must equal pk.G^s mod N.
//
// The verification equation (§4.2 of the paper):
//  1. Recompute H_prod = ∏ h(W_{i_j})^{a_j} mod N from the stored tags.
//  2. Recover g^μ = T^e / H_prod mod N.
//     This works because T^e = ∏(h(W_i)*g^m)^{d*e*a_j} = ∏ h(W_i)^{a_j} * g^{a_j*m_j}
//     = H_prod * g^μ, using d*e ≡ 1 mod p'q' (the order of QR_N).
//  3. Compute g^{sμ} = (g^μ)^s mod N and compare SHA-256(g^{sμ}) to proof.Rho.
//
// The exponent a_j is reduced mod sk.Phi before computing H_prod. This is valid
// by Lagrange's theorem: for any x ∈ QR_N, x^k = x^(k mod p'q'). The asymmetry
// with GenProof (which does not reduce a_j) is harmless; see math_test.go.
func CheckProof(pk *PublicKey, sk *SecretKey, s *big.Int, tags []*Tag, chal *Challenge, proof *Proof) (bool, error) {
	if chal.C < 1 || chal.C > len(tags) {
		return false, fmt.Errorf("challenge C=%d out of range [1, %d]", chal.C, len(tags))
	}

	perm := BuildPRP(chal.K1, len(tags))

	// H_prod = ∏ h(W_{i_j})^{a_j} mod N
	Hprod := big.NewInt(1)
	for j := 1; j <= chal.C; j++ {
		ij := perm[j-1]
		tag := tags[ij]

		aj := PRF(chal.K2, j)
		// By Lagrange's theorem, every element of QR_N has order dividing
		// p'q' = sk.Phi, so x^k ≡ x^(k mod p'q') (mod N) for all x ∈ QR_N.
		// Reducing a_j mod phi shrinks the exponent without changing the group
		// element, and does not affect the verification equation.
		aj.Mod(aj, sk.Phi)

		h := hashToQRN(tag.W, pk.N)
		term := new(big.Int).Exp(h, aj, pk.N)
		Hprod.Mul(Hprod, term)
		Hprod.Mod(Hprod, pk.N)
	}

	// Recover g^μ = T^e * H_prod^{-1} mod N
	Te := new(big.Int).Exp(proof.T, sk.E, pk.N)
	Hinv := new(big.Int).ModInverse(Hprod, pk.N)
	if Hinv == nil {
		return false, fmt.Errorf("H_prod has no inverse mod N")
	}
	gmu := new(big.Int).Mul(Te, Hinv)
	gmu.Mod(gmu, pk.N)

	// Compute g^{sμ} = (g^μ)^s and compare to the server's rho
	gsmu := new(big.Int).Exp(gmu, s, pk.N)
	expected := sha256.Sum256(gsmu.Bytes())

	return bytes.Equal(expected[:], proof.Rho), nil
}
