// Package ateniese implements the Scalable Provable Data Possession (S-PDP)
// protocol from "Provable Data Possession at Untrusted Stores" by Ateniese et al.
// (ACM CCS 2007). A copy of the paper is in doc/provable-data-possession.pdf.
//
// # Overview
//
// S-PDP lets a client (C) verify that a remote server (S) is faithfully storing
// a file without downloading the file. The protocol has three phases:
//
//  1. Setup: C splits the file into n blocks, generates a key pair, computes a
//     cryptographic tag for each block, and uploads the blocks and tags to S. C
//     then deletes its local copies of the blocks and tags, keeping only (pk, sk).
//
//  2. Challenge: C generates a random challenge that names a subset of blocks (via
//     a pseudorandom permutation) and sends it to S. The challenge also includes a
//     public blinding factor Gs = g^s, where s is a random secret C keeps private.
//
//  3. Response & Verification: S calls GenProof to produce an aggregated proof V
//     and returns it to C. C calls CheckProof with s to verify V.
//
// # Versioning
//
// Every Tag embeds a Suite ID so the verifier always knows which algorithm was
// used to create it. Pass a *pdp.Suite to TagBlock, GenProof, and CheckProof:
//
//	tag, err   := ateniese.TagBlock(pdp.SuiteV1, pk, sk, block, w)
//	proof, err := ateniese.GenProof(pdp.SuiteV1, pk, blocks, chal, tags)
//	ok, err    := ateniese.CheckProof(pdp.SuiteV1, pk, sk, s, tags, chal, proof)
//
// To introduce a new algorithm variant, define a new pdp.Suite with different
// function implementations and a new ID — existing tags remain verifiable
// against the suite that created them.
//
// # Deviations from the paper
//
// Block data is SHA-256 hashed before use as a group exponent (necessary for
// arbitrary-length blocks; applied identically in TagBlock and GenProof).
//
// pdp.SuiteV1 uses MGF1 (RFC 8017 §B.2.1) with SHA-256 for HashToQRN, producing
// a near-uniform full-domain hash over QR_N (paper footnote 3, bias < 2^{-128}).
//
// # Scheme variant
//
// This package implements S-PDP (§4.3 / Fig. 2), the variant with random
// per-block coefficients a_j drawn from a PRF keyed with k2. Because the
// coefficients are distinct and unpredictable, the server must possess each
// individually challenged block to produce a valid proof — the strong data
// possession guarantee. The paper also describes E-PDP (§4.3, "A more efficient
// scheme, with weaker guarantees"), where all a_j = 1, reducing server work to
// a single modular exponentiation but proving only possession of the sum of the
// challenged blocks. E-PDP is not implemented here.
//
// # Parameter choices
//
// The paper requires e to be a large secret prime with e > λ (§4.3 preamble).
// This implementation uses a 256-bit random prime for e, corresponding to
// λ = 256. The RSA modulus is approximately 2k bits for the k passed to KeyGen;
// the paper recommends k ≥ 1024 in production.
//
// # Lagrange's theorem
//
// For any x in QR_N and integer k, x^k ≡ x^(k mod p'q') mod N, because QR_N
// is a cyclic group of order p'q' (Lagrange's theorem). CheckProof exploits
// this by reducing a_j mod phi = p'q' before computing h(W)^{a_j}, avoiding
// large-integer exponentiation without changing the group element. GenProof
// does not explicitly reduce a_j before computing tag^{a_j}; the result is
// identical because the same theorem applies. See TestExponentReductionModGroupOrder
// and TestMuReductionEquivalence in math_test.go for proof by example.
package ateniese

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"fmt"
	"math/big"

	"github.com/pinionengineering/storage-proofs/pdp"
	"github.com/pinionengineering/storage-proofs/suite"
)

// SecretKey is the client's private key. It must never be sent to the server.
//
//   - E and D satisfy E*D ≡ 1 (mod Phi); E is the RSA encryption exponent and
//     D is the decryption (tag-signing) exponent.
//   - V is a random secret used to derive per-block identifiers W_i = V || i.
//   - Phi = p'*q' is the order of QR_N, used for exponent reduction in CheckProof.
type SecretKey struct {
	E   *big.Int
	D   *big.Int
	V   []byte
	Phi *big.Int
}

// Tag is the verification metadata for a single file block, computed by TagBlock.
//
//   - SuiteID identifies the algorithm suite used to create the tag.
//   - T is the tag value: T = (h(W) * g^m)^d mod N.
//   - W is the block identifier W_i = V || i, kept alongside T so the verifier
//     can recompute h(W_i) during CheckProof without access to V.
type Tag struct {
	SuiteID uint8
	T       *big.Int
	W       []byte
}

// Challenge is generated by the client and sent to the server to initiate an audit.
//
//   - SuiteID identifies which algorithm suite must be used to process this
//     challenge. K1 and K2 are only meaningful relative to the suite's PRF and
//     PRP implementations; a different suite would produce different block
//     selections and coefficients from the same keys. GenProof and CheckProof
//     both verify that the challenge's SuiteID matches the suite they are called
//     with and the SuiteID embedded in the tags.
//   - C is the number of blocks to challenge (must satisfy 1 <= C <= len(blocks)).
//   - K1 is a random key for the pseudorandom permutation that selects block indices.
//   - K2 is a random key for the pseudorandom function that assigns per-block coefficients.
//   - Gs is the public blinding factor g^s, where s is a random secret kept by the client.
//     The server uses Gs to compute rho = H((g^s)^μ) without learning s. The client
//     passes s (not Gs) to CheckProof to verify the response.
type Challenge struct {
	SuiteID uint8
	C       int
	K1      []byte
	K2      []byte
	Gs      *big.Int // g^s: public blinding factor; the client keeps s secret
}

// Proof is the server's response to a Challenge, produced by GenProof.
//
//   - T is the aggregated tag product: T = ∏ tag_i^{a_j} mod N.
//   - Rho is the binding hash: rho = SHA-256((g^s)^μ mod N), where μ = Σ a_j*m_j.
type Proof struct {
	T   *big.Int
	Rho []byte
}

// ---------------------------------------------------------------------------
// Key generation
// ---------------------------------------------------------------------------

// KeyGen generates a fresh key pair for the S-PDP scheme.
//
// k is the security parameter in bits; it controls the size of the safe primes
// used to build the RSA modulus (N is approximately 2k bits). The paper requires
// k ≥ 1024 for security; smaller values (e.g. k = 128) are only suitable for tests.
//
// Key generation is independent of the algorithm suite. The same key pair can
// be used with any pdp.Suite.
//
// The algorithm (§4.3 / Fig. 2, KeyGen):
//  1. Generate safe primes p = 2p'+1 and q = 2q'+1; set N = p*q. (§4.3 preamble)
//  2. Set phi = p'*q', the order of QR_N. (§4.3 preamble)
//  3. Choose a random 256-bit prime e coprime to phi; compute d = e^{-1} mod phi.
//     The paper requires e > λ (a large secret prime, §4.3 preamble); λ = 256 here.
//  4. Generate g, a generator of QR_N. (§4.3 preamble)
//  5. Draw a random secret v ∈ {0,1}^k, used to derive per-block identifiers.
func KeyGen(k int) (pk *pdp.PublicKey, sk *SecretKey, err error) {
	p, pPrime, err := pdp.GenerateSafePrime(k)
	if err != nil {
		return nil, nil, err
	}
	q, qPrime, err := pdp.GenerateSafePrime(k)
	if err != nil {
		return nil, nil, err
	}

	N := new(big.Int).Mul(p, q)

	// phi = p'*q' is the order of QR_N.
	// Note: the full Euler totient is phi(N) = (p-1)(q-1) = 4*p'*q', but the
	// relevant group order for elements of QR_N is p'*q'.
	phi := new(big.Int).Mul(pPrime, qPrime)

	// e is a 256-bit prime chosen coprime to phi.
	one := big.NewInt(1)
	var e *big.Int
	for {
		e, err = rand.Prime(rand.Reader, 256)
		if err != nil {
			return nil, nil, err
		}
		if new(big.Int).GCD(nil, nil, e, phi).Cmp(one) == 0 {
			break
		}
	}

	// d = e^{-1} mod phi; together e and d form the RSA trapdoor over QR_N.
	d := new(big.Int).ModInverse(e, phi)
	if d == nil {
		return nil, nil, fmt.Errorf("mod inverse of e mod phi failed")
	}

	g, err := pdp.GenerateGQRN(N)
	if err != nil {
		return nil, nil, err
	}

	v := make([]byte, k/8)
	if _, err = rand.Read(v); err != nil {
		return nil, nil, err
	}

	pk = &pdp.PublicKey{N: N, G: g}
	sk = &SecretKey{E: e, D: d, V: v, Phi: phi}
	return pk, sk, nil
}

// ---------------------------------------------------------------------------
// Protocol operations
// ---------------------------------------------------------------------------

// TagBlock computes the verification tag for block m with block identifier w.
//
// w is the full block identifier stored in the returned Tag.W field. The caller
// is responsible for constructing w — a typical choice is V || encode(index),
// which binds the tag to both the key pair (via V) and the block's position.
// Other schemes (e.g. V || CID bytes for a content-addressed DAG) are equally
// valid as long as w is unique within the key pair's scope.
//
// The algorithm (§4.3 / Fig. 2, TagBlock):
//  1. W_i = v||i; T_{i,m} = (h(W_i) · g^m)^d mod N. (Fig. 2, TagBlock step 1)
//  2. Output (T_{i,m}, W_i). (Fig. 2, TagBlock step 2)
//
// Interface note: the paper's TagBlock(pk, sk, m, i) computes W_i = v||i
// internally. Here the caller pre-computes w so that non-index identifiers
// (e.g. CID bytes for a content-addressed DAG) are also supported. The standard
// W_i = V||encode(i) construction for sequential file blocks is shown in the tests.
//
// Deviation from the paper: m is SHA-256 hashed before being used as a group
// exponent, mapping arbitrary-length block data to a fixed 256-bit integer.
// GenProof applies the same hash, so the verification equation is unaffected.
//
// The tags (but not sk.V) are sent to the server along with the blocks.
func TagBlock(s *suite.Suite, pk *pdp.PublicKey, sk *SecretKey, m []byte, w []byte) (*Tag, error) {
	mInt := s.HashBlock(m)

	h := s.HashToQRN(w, pk.N)                // h(w) ∈ QR_N
	gm := new(big.Int).Exp(pk.G, mInt, pk.N) // g^m mod N
	T := new(big.Int).Mul(gm, h)             // h(w) * g^m
	T.Mod(T, pk.N)
	T.Exp(T, sk.D, pk.N) // (h(w) * g^m)^d mod N

	return &Tag{SuiteID: s.ID(), T: T, W: w}, nil
}

// GenProof is run by the server to produce a proof of possession for the challenged blocks.
//
// All tags must carry the same SuiteID as s; GenProof returns an error on any
// mismatch so the server never silently uses the wrong algorithm.
//
// The algorithm (§4.3 / Fig. 2, GenProof):
//  1. For 1 ≤ j ≤ C: i_j = π_{k1}(j) via BuildPRP; a_j = f_{k2}(j) via PRF.
//     (Fig. 2, GenProof step 1)
//  2. T = ∏ tag_{i_j}^{a_j} mod N. (Fig. 2, GenProof step 2)
//  3. μ = Σ a_j · SHA-256(block_{i_j}) as an unreduced integer.
//     ρ = SHA-256(g_s^μ mod N), where g_s = chal.Gs = g^s.
//     (Fig. 2, GenProof step 3; SHA-256 of the block is the deviation noted above.)
//  4. Return V = (T, ρ). (Fig. 2, GenProof step 4)
//
// blocks and tags must be the same length and chal.C must be in [1, len(blocks)].
func GenProof(s *suite.Suite, pk *pdp.PublicKey, blocks [][]byte, chal *Challenge, tags []*Tag) (*Proof, error) {
	if chal.SuiteID != s.ID() {
		return nil, fmt.Errorf("challenge suite %d does not match suite %d", chal.SuiteID, s.ID())
	}
	if len(blocks) != len(tags) {
		return nil, fmt.Errorf("blocks and tags length mismatch: %d vs %d", len(blocks), len(tags))
	}
	if chal.C < 1 || chal.C > len(blocks) {
		return nil, fmt.Errorf("challenge C=%d out of range [1, %d]", chal.C, len(blocks))
	}

	// §4.3 Fig. 2, GenProof step 1: i_j = π_{k1}(j).
	perm := s.BuildPRP(chal.K1, len(blocks))

	T := big.NewInt(1)
	mu := big.NewInt(0)

	for j := 1; j <= chal.C; j++ {
		ij := perm[j-1]
		tag := tags[ij]

		if tag.SuiteID != s.ID() {
			return nil, fmt.Errorf("tag[%d] suite %d does not match suite %d", ij, tag.SuiteID, s.ID())
		}

		aj := s.PRF(chal.K2, j) // a_j = f_{k2}(j), §4.3 Fig. 2 step 1

		// §4.3 Fig. 2, GenProof step 2: T = ∏ tag_{i_j}^{a_j} mod N.
		term := new(big.Int).Exp(tag.T, aj, pk.N)
		T.Mul(T, term)
		T.Mod(T, pk.N)

		// §4.3 Fig. 2, GenProof step 3: accumulate μ = Σ a_j · m_{i_j}.
		mu.Add(mu, new(big.Int).Mul(aj, s.HashBlock(blocks[ij])))
	}

	// §4.3 Fig. 2, GenProof step 3: ρ = SHA-256(g_s^μ mod N).
	gsmu := new(big.Int).Exp(chal.Gs, mu, pk.N)
	rho := sha256.Sum256(gsmu.Bytes())

	return &Proof{T: T, Rho: rho[:]}, nil // §4.3 Fig. 2, GenProof step 4
}

// CheckProof is run by the client to verify a proof returned by the server.
//
// secret is the client's per-challenge secret s (not transmitted to the server).
// chal.Gs must equal pk.G^secret mod N.
//
// All tags must carry the same SuiteID as s; CheckProof returns an error on any mismatch.
//
// The verification equation (§4.3 / Fig. 2, CheckProof):
//  1. Unpack chal and proof. (Fig. 2, CheckProof step 1)
//  2. Compute H_prod = ∏ h(W_{i_j})^{a_j} mod N. (Fig. 2, CheckProof step 2)
//     The paper describes iterative division: start with τ = T^e and divide by
//     h(W_{i_j})^{a_j} for each j. We batch the denominator product and invert
//     once — algebraically identical. a_j is reduced mod phi = p'q' here via
//     Lagrange's theorem (see package doc); GenProof does not reduce a_j.
//  3. Recover g^μ = T^e · H_prod^{-1} mod N. (Fig. 2, CheckProof step 2)
//     T^e = ∏(h(W_i)·g^m)^{d·e·a_j} = H_prod · g^μ, since d·e ≡ 1 mod p'q'.
//  4. Check SHA-256((g^μ)^s mod N) = ρ. (Fig. 2, CheckProof step 3)
func CheckProof(s *suite.Suite, pk *pdp.PublicKey, sk *SecretKey, secret *big.Int, tags []*Tag, chal *Challenge, proof *Proof) (bool, error) {
	if chal.SuiteID != s.ID() {
		return false, fmt.Errorf("challenge suite %d does not match suite %d", chal.SuiteID, s.ID())
	}
	if chal.C < 1 || chal.C > len(tags) {
		return false, fmt.Errorf("challenge C=%d out of range [1, %d]", chal.C, len(tags))
	}

	// §4.3 Fig. 2, CheckProof step 1: i_j = π_{k1}(j).
	perm := s.BuildPRP(chal.K1, len(tags))

	// §4.3 Fig. 2, CheckProof step 2: compute H_prod = ∏ h(W_{i_j})^{a_j} mod N.
	// The paper iteratively divides τ = T^e by each h(W)^{a_j}; we accumulate the
	// product and invert once — the result is algebraically identical.
	Hprod := big.NewInt(1)
	for j := 1; j <= chal.C; j++ {
		ij := perm[j-1]
		tag := tags[ij]

		if tag.SuiteID != s.ID() {
			return false, fmt.Errorf("tag[%d] suite %d does not match suite %d", ij, tag.SuiteID, s.ID())
		}

		aj := s.PRF(chal.K2, j) // a_j = f_{k2}(j), §4.3 Fig. 2 step 1
		// Lagrange's theorem: |QR_N| = p'q', so h(W)^{a_j} ≡ h(W)^{a_j mod p'q'} mod N.
		// Reducing a_j avoids a large-integer exponentiation. GenProof does not reduce
		// a_j for tag^{a_j} — the same theorem applies, so both sides agree.
		aj.Mod(aj, sk.Phi)

		h := s.HashToQRN(tag.W, pk.N)
		term := new(big.Int).Exp(h, aj, pk.N)
		Hprod.Mul(Hprod, term)
		Hprod.Mod(Hprod, pk.N)
	}

	// §4.3 Fig. 2, CheckProof step 2: recover g^μ = T^e · H_prod^{-1} mod N.
	// T^e = ∏(h(W_i)·g^m)^{d·e·a_j} = H_prod · g^μ, since d·e ≡ 1 mod p'q'.
	Te := new(big.Int).Exp(proof.T, sk.E, pk.N)
	Hinv := new(big.Int).ModInverse(Hprod, pk.N)
	if Hinv == nil {
		return false, fmt.Errorf("H_prod has no inverse mod N")
	}
	gmu := new(big.Int).Mul(Te, Hinv)
	gmu.Mod(gmu, pk.N)

	// §4.3 Fig. 2, CheckProof step 3: check SHA-256((g^μ)^s mod N) = ρ.
	gsmu := new(big.Int).Exp(gmu, secret, pk.N)
	expected := sha256.Sum256(gsmu.Bytes())

	return bytes.Equal(expected[:], proof.Rho), nil
}
