// Package sw implements the private-key Proof of Retrievability scheme from
// "Compact Proofs of Retrievability" by Hovav Shacham and Brent Waters
// (ASIACRYPT 2008, §3).
//
// Unlike the bounded-challenge BJO scheme in package por/bjo, the SW
// private-key scheme supports an unlimited number of audits: challenges are
// generated fresh from randomness each time and do not consume precomputed
// state on the client.
//
// # Protocol overview
//
// Each file block is divided into S sectors. Setup computes one tag per block:
//
//	σ_i = PRF_K(i) + Σ_{j=1}^S f_{i,j}·α_j  mod P
//
// where f_{i,j} = SetBytes(sector j of block i) mod P and α_1,...,α_S are
// secret scalars. The client uploads the file and tags to the server, then
// discards both, keeping only the secret key (K, α).
//
// Each audit:
//
//  1. Client picks L random (block index, coefficient) pairs (i_t, ν_t) and
//     sends them as a Challenge.
//  2. Server computes (§3):
//
//	   σ  = Σ_t ν_t · σ_{i_t}              mod P
//	   μ_j = Σ_t ν_t · f_{i_t,j}           mod P  for j = 1,...,S
//
//  3. Client verifies (§3):
//
//	   σ == Σ_t ν_t · PRF_K(i_t) + Σ_j μ_j · α_j  mod P
//
// Correctness follows by substituting the tag definition into σ and grouping
// terms; the identity holds algebraically for any honest response.
//
// # Unlimited challenges
//
// BJO precomputes Q sentinel ciphertexts at setup and consumes one per audit,
// bounding total audits at Q. SW has no such precomputed state: each challenge
// is drawn independently from random, so audits are unlimited.
//
// # Proof size
//
// Each audit response is S+1 elements of Z_P: one σ and S μ_j values. BJO
// returns a single Z_P element per audit (plus the sentinel ciphertext). SW
// proofs grow linearly in S, so the sector count trades proof size against the
// P > max(sector value) constraint: more sectors → smaller sectors → smaller
// P needed → smaller Z_P elements.
//
// # Deviations from the paper
//
// PRF: §3 leaves the PRF unspecified. This implementation delegates to a
// pdp.Suite PRF (see package pdp). The PRF must produce at least 256-bit
// output so that the statistical bias when reducing mod P is at most
// P/2^256 ≤ 2^{-128} for any P ≤ 2^128. All suites in package pdp satisfy
// this requirement. Use pdp.SuiteV1 (HMAC-SHA256) for the most conservative
// choice; see pdp.Suite for alternatives.
package sw

import (
	"crypto/rand"
	"fmt"
	"math/big"

	"github.com/pinionengineering/storage-proofs/suite"
)

// ---------------------------------------------------------------------------
// Protocol types
// ---------------------------------------------------------------------------

// Params holds the public system parameters for the SW scheme.
type Params struct {
	// S is the number of sectors per block. Each block is split into S
	// equal-sized byte slices, each interpreted as a Z_P element.
	// Larger S reduces the sector size (relaxing the P > max(sector value)
	// constraint for extraction) and increases proof size (S μ_j per audit).
	S int

	// L is the number of blocks sampled per challenge. Higher L gives tighter
	// per-round soundness (probability a cheating server goes undetected ≈
	// (1 − corrupt_fraction)^L) at the cost of more server I/O per audit.
	L int

	// P is the prime field modulus. Must satisfy P > 2^(8·ceil(blockSize/S))
	// for the extraction property (sector bytes map injectively into Z_P).
	// For the basic challenge/verify protocol any prime works.
	P *big.Int
}

// SecretKey is the client's secret key. It is never transmitted to the server.
type SecretKey struct {
	// K is the PRF key. tagPRF(K, i) provides the pseudorandom per-block
	// offset that binds tag σ_i to block i without revealing file content.
	K []byte

	// Alpha is the vector (α_1,...,α_S) of secret scalars in Z_P.
	Alpha []*big.Int

	Params *Params
}

// Tag is the per-block verification metadata stored on the server.
// σ_i = PRF_K(i) mod P + Σ_{j=1}^S f_{i,j}·α_j mod P.
type Tag struct {
	Sigma *big.Int
}

// Challenge is generated by the client and sent to the server.
type Challenge struct {
	// Indices is the list of L distinct block indices (0-based) to audit.
	Indices []int
	// Coeffs is the list of L random blinding factors ν_t ∈ Z_P.
	Coeffs []*big.Int
}

// Proof is the server's response to a Challenge.
type Proof struct {
	// Sigma = Σ_t ν_t · σ_{i_t} mod P.
	Sigma *big.Int
	// Mu[j-1] = Σ_t ν_t · f_{i_t,j} mod P for j = 1,...,S.
	Mu []*big.Int
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// sectorElem returns the j-th sector of block (0-indexed) as a Z_P element.
// The block is divided into s equal-sized slices; the last slice may be shorter.
// Returns 0 for j beyond the block (zero padding for short blocks).
func sectorElem(block []byte, j, s int, P *big.Int) *big.Int {
	n := len(block)
	sectorSize := (n + s - 1) / s
	start := j * sectorSize
	if start >= n {
		return big.NewInt(0)
	}
	end := start + sectorSize
	if end > n {
		end = n
	}
	return new(big.Int).Mod(new(big.Int).SetBytes(block[start:end]), P)
}

// ---------------------------------------------------------------------------
// Protocol functions
// ---------------------------------------------------------------------------

// KeyGen generates a fresh SecretKey for the SW scheme.
// S random scalars α_j and a 32-byte PRF key K are drawn from the system
// random source.
func KeyGen(params *Params) (*SecretKey, error) {
	k := make([]byte, 32)
	if _, err := rand.Read(k); err != nil {
		return nil, fmt.Errorf("sw.KeyGen: %w", err)
	}

	alpha := make([]*big.Int, params.S)
	for j := range params.S {
		a, err := rand.Int(rand.Reader, params.P)
		if err != nil {
			return nil, fmt.Errorf("sw.KeyGen: alpha[%d]: %w", j, err)
		}
		alpha[j] = a
	}

	return &SecretKey{K: k, Alpha: alpha, Params: params}, nil
}

// TagFile computes one Tag per block and returns them in order.
//
// The client uploads the file and tags to the server, then discards both,
// retaining only sk.
//
// σ_i = PRF_K(i) mod P + Σ_{j=1}^S f_{i,j}·α_j  mod P
func TagFile(s *suite.Suite, sk *SecretKey, file [][]byte) []*Tag {
	p := sk.Params
	tags := make([]*Tag, len(file))
	for i, block := range file {
		sigma := new(big.Int).Mod(s.PRF(sk.K, i), p.P)
		for j := range p.S {
			fij := sectorElem(block, j, p.S, p.P)
			sigma.Add(sigma, new(big.Int).Mul(fij, sk.Alpha[j]))
			sigma.Mod(sigma, p.P)
		}
		tags[i] = &Tag{Sigma: sigma}
	}
	return tags
}

// MakeChallenge generates a fresh random challenge for a file of n blocks.
// L distinct indices are chosen uniformly from [0, n); each is paired with a
// random coefficient in Z_P. The challenge can be generated any number of
// times without consuming stored state.
func MakeChallenge(n int, params *Params) (*Challenge, error) {
	if n <= 0 {
		return nil, fmt.Errorf("sw.MakeChallenge: n must be positive")
	}

	l := params.L
	if l > n {
		l = n
	}

	// Fisher-Yates partial shuffle to pick l distinct indices from [0, n).
	perm := make([]int, n)
	for i := range n {
		perm[i] = i
	}
	for i := range l {
		jBig, err := rand.Int(rand.Reader, big.NewInt(int64(n-i)))
		if err != nil {
			return nil, fmt.Errorf("sw.MakeChallenge: index %d: %w", i, err)
		}
		j := i + int(jBig.Int64())
		perm[i], perm[j] = perm[j], perm[i]
	}

	indices := make([]int, l)
	copy(indices, perm[:l])

	coeffs := make([]*big.Int, l)
	for t := range l {
		v, err := rand.Int(rand.Reader, params.P)
		if err != nil {
			return nil, fmt.Errorf("sw.MakeChallenge: coeff %d: %w", t, err)
		}
		coeffs[t] = v
	}

	return &Challenge{Indices: indices, Coeffs: coeffs}, nil
}

// RespondFetch is the core server-side proof function. It calls fetch(idx) for
// each challenged block index to obtain raw bytes, accumulates the linear
// combination across sectors and tags, and returns the proof.
//
// Only the L challenged blocks are fetched; the remaining n-L are not accessed.
func RespondFetch(params *Params, tags []*Tag, chal *Challenge, fetch func(idx int) ([]byte, error)) (*Proof, error) {
	P := params.P
	sigma := big.NewInt(0)
	mu := make([]*big.Int, params.S)
	for j := range params.S {
		mu[j] = big.NewInt(0)
	}

	for t, idx := range chal.Indices {
		if idx < 0 || idx >= len(tags) {
			return nil, fmt.Errorf("sw.RespondFetch: index %d out of range [0, %d)", idx, len(tags))
		}
		nu := chal.Coeffs[t]

		data, err := fetch(idx)
		if err != nil {
			return nil, fmt.Errorf("sw.RespondFetch: block %d: %w", idx, err)
		}

		// σ += ν_t · σ_{i_t}
		sigma.Add(sigma, new(big.Int).Mul(nu, tags[idx].Sigma))
		sigma.Mod(sigma, P)

		// μ_j += ν_t · f_{i_t,j}
		for j := range params.S {
			fij := sectorElem(data, j, params.S, P)
			mu[j].Add(mu[j], new(big.Int).Mul(nu, fij))
			mu[j].Mod(mu[j], P)
		}
	}

	return &Proof{Sigma: sigma, Mu: mu}, nil
}

// Respond is run by the server to answer a challenge.
// It reads blocks directly from file and delegates to RespondFetch.
func Respond(params *Params, file [][]byte, tags []*Tag, chal *Challenge) (*Proof, error) {
	return RespondFetch(params, tags, chal, func(idx int) ([]byte, error) {
		if idx < 0 || idx >= len(file) {
			return nil, fmt.Errorf("index %d out of range", idx)
		}
		return file[idx], nil
	})
}

// Verify checks whether the server's proof is valid.
//
// It recomputes the expected σ from the challenge, the PRF key K, and the
// secret scalars α, then compares it to proof.Sigma.
//
// §3: "σ == Σ_t ν_t·PRF_K(i_t) + Σ_j μ_j·α_j  mod P"
func Verify(s *suite.Suite, sk *SecretKey, chal *Challenge, proof *Proof) (bool, error) {
	p := sk.Params
	P := p.P

	if len(proof.Mu) != p.S {
		return false, fmt.Errorf("sw.Verify: proof has %d μ elements, want %d", len(proof.Mu), p.S)
	}

	expected := big.NewInt(0)

	// Σ_t ν_t · PRF_K(i_t) mod P
	for t, idx := range chal.Indices {
		nu := chal.Coeffs[t]
		prf := new(big.Int).Mod(s.PRF(sk.K, idx), P)
		expected.Add(expected, new(big.Int).Mul(nu, prf))
		expected.Mod(expected, P)
	}

	// Σ_j μ_j · α_j mod P
	for j := range p.S {
		expected.Add(expected, new(big.Int).Mul(proof.Mu[j], sk.Alpha[j]))
		expected.Mod(expected, P)
	}

	return proof.Sigma.Cmp(expected) == 0, nil
}
